name = input("Enter your name: ")
age = input("Enter your age: ")
course = input("Enter your course: ")
college = input("Enter your college name: ")

print("\nPersonal Details")
print("----------------")
print("Name   :", name)
print("Age    :", age)
print("Course :", course)
print("College:", college)